name: Infra Vending Machine

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'S3 Bucket Name'
        required: false
      table_name:
        description: 'DynamoDB Table Name'
        required: false
      inst_name:
        description: 'EC2 Instance Name'
        required: false
      inst_type:
        description: 'EC2 Instance Type'
        default: 't3.micro'
        required: false
      st_reqd:
        description: 'EC2 Storage Required'
        default: 8
        required: false
      environment:
        description: 'Environment'
        default: 'dev'
        required: false

jobs:
  deploy-S3:
    if: inputs.bucket_name != ''
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'
    - name: Terraform Init
      working-directory: modules/s3
      run: |
        terraform init -backend-config="bucket=kratos-state-files" -backend-config="key=vending-machine/${{ inputs.bucket_name }}.tfstate" -backend-config="region=ap-south-1"
    - name: Terraform Apply
      working-directory: modules/s3
      run: |
        terraform apply -auto-approve -var="bucket_name=${{ inputs.bucket_name }}"

  deploy-dynamodb:
    if: inputs.table_name != ''
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'
    - name: Terraform Init
      working-directory: modules/dynamo_db
      run: |
        terraform init -backend-config="bucket=kratos-state-files" -backend-config="key=vending-machine/${{ inputs.table_name }}.tfstate" -backend-config="region=ap-south-1"
    - name: Terraform Apply
      working-directory: modules/dynamo_db
      run: |
        terraform apply -auto-approve -var="table_name=${{ inputs.table_name }}"

  deploy-EC2:
    if: inputs.inst_name != ''
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'
    - name: Terraform Init
      working-directory: modules/ec2
      run: |
        terraform init -backend-config="bucket=kratos-state-files" -backend-config="key=vending-machine/${{ inputs.inst_name }}.tfstate" -backend-config="region=ap-south-1"
    - name: Terraform Apply
      working-directory: modules/ec2
      run: |
        terraform apply -auto-approve -var="inst_name=${{ inputs.inst_name }}" -var="st_reqd=${{ inputs.st_reqd }}" -var="inst_type=${{ inputs.inst_type }}"
